version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always